/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer */

#ifndef _Included_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
#define _Included_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
 * Method:    create_rtp_player
 * Signature: (Landroid/view/Surface;)J
 */
JNIEXPORT jlong JNICALL Java_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer_create_1rtp_1player
  (JNIEnv *, jobject, jobject);

/*
 * Class:     zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
 * Method:    add_stream
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer_add_1stream
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
 * Method:    video_info
 * Signature: (J)Lzhaopeng/com/rtpplayer/rtpplayer/VideoInfo;
 */
JNIEXPORT jobject JNICALL Java_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer_video_1info
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
 * Method:    audio_info
 * Signature: (J)Lzhaopeng/com/rtpplayer/rtpplayer/AudioInfo;
 */
JNIEXPORT jobject JNICALL Java_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer_audio_1info
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
 * Method:    get_play_time_ms
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer_get_1play_1time_1ms
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer
 * Method:    destroy_rtp_player
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_zhaopeng_com_rtpplayer_rtpplayer_RtpPlayer_destroy_1rtp_1player
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
